# def catch_and_throw(value)
  
#   puts value
#   a = readline.chomp
  
#   # using throw statement
#   throw :value_e if a == "!"
#   return a
  
# end
  
# # using catch statement
# catch :value_e do
  
# # enter number
#   number = catch_and_throw("Enter Number: ")
# end

# var = gets.chomp
# throw :name if var==0
# return var

# catch:name do
#   puts "Input error"
# end